- Package.resolved
- Sources/VitalHealthKit/Extensions/Date.swift
- Sources/VitalHealthKit/Extensions/HKHealthStore.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
`dateOfBirthComponents()` is not exposed to Swift correctly.
The scenario of "permission granted but DoB unset" is represented by `*error = nil` + returning `nil`. But this pattern is instead recognised (1) by the Swift-ObjC interop as erroring without any NSError; and (2) the Clang importer as non-null returning method.
Workaround the issue by catching the `Foundation._GenericObjCError` being thrown by the interop runtime in absence of an actual NSError.
Also explicitly set `Gregorian` on the date components when interpreting HealthKit-returned DoB, in case the current calendar is not Gregorian (rare but possible).
> [VIT-2429] Workaround incorrectly imported dateOfBirthComponents()

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Examples/iOS/Devices Tab/Models/Devices+Support.swift
- Sources/VitalDevices/DeviceManager+Brands.swift
- Sources/VitalDevices/DeviceManager.swift
- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/Errors.swift
- Sources/VitalDevices/DeviceReading/GlucoseMeter1808.swift
- Sources/VitalDevices/DeviceReading/RACPResponse.swift
- Sources/VitalDevices/Models/SFloat.swift
Improve the BLE Glucose Service (1808) reader in VitalDevices:
1. Fixed unit handling: Now handles both kg/L and mol/L correctly as per BLE spec.
2. Fixed binary payload decoding: Respect flags and optional frames; handle the sfloat format correctly.
3. The `GlucoseMeter.read(device:)` publisher now either completes with one batch of all stored records, or error out. This is new change from the current behaviour (never ending publisher, with samples in chunks). 
* This is achieved by listening to the RACP response indication (notification), which must be issued by a compliant device after they have finished sending out all the measurements via BLE notifications, or when an error is encountered.
4. Added device support for Vital BLE Simulator.
Note: Blood Pressure service to be improved …
> VIT-2513 BLE Glucose Service reader improvements

- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/GATTMeter.swift
- Sources/VitalDevices/DeviceReading/GlucoseMeter1808.swift
Apply improvements in #21 to the Blood Pressure reader as well, by factoring out the common a BLE GATT Service reader implementation.
> VIT-2516 Factor out GATTMeter base class & reuse in BLE BP reader

- Sources/VitalDevices/DeviceReading/RACPResponse.swift
Turns out we have missed a byte, according to the Nordic Semi Android BLE SDK.
> VIT-2516 Fix RACP response payload parsing

- BLEMonitorSimulator/BLEMonitorSimulator.xcodeproj/project.pbxproj
- BLEMonitorSimulator/BLEMonitorSimulator.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- BLEMonitorSimulator/BLEMonitorSimulator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- BLEMonitorSimulator/BLEMonitorSimulator.xcodeproj/xcshareddata/xcschemes/BLEMonitorSimulator.xcscheme
- BLEMonitorSimulator/BLEMonitorSimulator/Assets.xcassets/AccentColor.colorset/Contents.json
- BLEMonitorSimulator/BLEMonitorSimulator/Assets.xcassets/AppIcon.appiconset/Contents.json
- BLEMonitorSimulator/BLEMonitorSimulator/Assets.xcassets/Contents.json
- BLEMonitorSimulator/BLEMonitorSimulator/BLEMonitorSimulatorApp.swift
- BLEMonitorSimulator/BLEMonitorSimulator/ContentView.swift
- BLEMonitorSimulator/BLEMonitorSimulator/GlucoseMonitorSimulation.swift
- BLEMonitorSimulator/BLEMonitorSimulator/Info.plist
- BLEMonitorSimulator/BLEMonitorSimulator/Preview Content/Preview Assets.xcassets/Contents.json
- BLEMonitorSimulator/BLEMonitorSimulator/SFloat.swift
- BLEMonitorSimulator/BLEMonitorSimulatorTests/SFloatTests.swift
A Mac Catalyst app that emulates BLE Glucose Monitor service via Core Bluetooth.
* Requires #21 which added support for the "Vital BLE Simulator" device type.
* Does not fully implement the Service Specification, but only the parts where Vital Devices rely upon.
> VIT-2518 BLE Simulator for Glucose Monitor

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalDevices/DeviceManager.swift
Create an iOS equivalent of vital-android's new `VitalDevicesManager.connected(DeviceModel)` in https://github.com/tryVital/vital-android/pull/15.
API consumers can query currently connected BLE devices via `connected(DeviceModel)`. On iOS, connections can reset upon app being backgrounded/suspended/termination, so not all paired devices would show up w/o re-scanning.
Note that Android has a stronger semantic with this API, since the Android BLE stack would persistently report also paired-but-disconnected devices, but we are framing this as "connected devices" for platform parity.
This is useful for speeding up device listing (when connected) and general troubleshooting.
An introspection API to check if the SDK has been configured or not.
For example, the example app Device screen now …
> [VIT-2593] Support listing currently connected BLE devices

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalStatistics.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/VitalHealthKitClientTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
* Stop using the `separateBySource` option, so HKStatisticsCollectionQuery would merge all sources and produce one set of statistics only
* Currently, with `separateBySource`, HealthKit computes one set of statistics individually for each source that has samples within the specified time interval. So if there are 5 sources, we will forward to the backend 5 sets of statistics that are overlapping within the same time frame. This is not the semantic we want; what we want is to report a timeseries per sample type that would resemble the numbers shown by the Apple Health app, which are numbers merged by HealthKit from all sources based on the user's source priority preference.
* This is crucial for matching statistics reported in the Apple Health app, specifically for certain sample types …
> Statistics with HealthKit source merging

- Sources/VitalHealthKit/Extensions/Date.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalStatistics.swift
- Tests/VitalHealthKitTests/VitalHealthKitAnchorTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
For each hourly statistics point, ask `HKSampleQuery` for the first and the last sample that falls in the hour time interval. Then use their `startDate` to populate `firstSampleDate` and `lastSampleDate`.
This reduces the time complexity from O(n<sup>2</sup>) to O(n*log(n)), assuming HealthKit does internally fulfil time range predicates using indexes. It also avoids the need to dump all matching samples into memory.
120 days backfill, 6.8x speedup
1m 49s
3 low memory warnings + over CPU budget
16s
> [WIP] Optimize VitalStatistics enrichment

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
We perform a HKStatisticsCollectionQuery w/o strictStartDate and strictEndDate in order to have aggregates matching numbers in the Health app.
However, a caveat is that HealthKit can often return incomplete statistics point outside the query interval we specified. While including samples astriding the bounds would desirably contribute to stat points we are interested in, as a byproduct of the bucketing process (in our case, hourly buckets), HealthKit would also create stat points from the unwanted portion of these samples.
These unwanted stat points must be explicitly discarded, since they are not backed by the complete set of samples within their representing time interval (as they are rightfully excluded by the query interval we specified).
say we have five step samples:
- 2022-01-02 …
> [VIT-2666] Workaround a HKStatCollectionQuery quirk

- Sources/VitalCore/Calendar/GregorianCalendar.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/ActivityPatch.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Get/Source/APIClient.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalStatistics.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
An activity day summary is aggregated from 5 sample types, containing 5 sums for a specific calendar day in the device TZ.
The SDK now computes day summaries as part of `handleActivity(...)`, specifically:
1. ~~A new `StoredAnchor` is dedicated to track when the last activity day summary was computed.~~
2. Given the last computed time and the current wall time, we enumerate all the floating dates that lie within this time interval with respect to the device TZ.
* e.g.1., if both last computed and current wall time both lie in `2023-01-02` in the device TZ, only `2023-01-02` would be enumerated.
* e.g.1., if last computed lies in `2022-12-31` in the device TZ, and that of the current wall time was `2023-01-02`, `2022-12-31`, `2023-01-01` and `2023-01-02` would be enumerated.
* The number …
> [VIT-2638] Activity day summaries.

- Sources/VitalCore/Core/Client/Data Models/Patches/Provider.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/TaggedPayload.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Endpoints+Extensions.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Link.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Summary.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Storage/VitalCoreStorage.swift
- Sources/VitalDevices/DeviceManager+Brands.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalCoreTests/ProviderTests.swift
- Tests/VitalCoreTests/VitalClientTests.swift
Merge the provider enum and the FullProvider struct into one model type, so that we don't expose two methods that are ultimately mapped to the same endpoint.
Also for API forward compatibility, adopted RawRepresentable struct over enum for the typed source slug. This enables new provider slugs returned by the API but unrecognised by the SDK to still be parsed, inspected & used, whereas the decoding would fail upon unrecognised value if it remained as an enum.
> [VIT-2671] Merge Provider and FullProvider types

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
lastSampleDate currently uses (equivalent of) `SELECT endDate ORDER BY startDate DESC LIMIT 1`. This can go wrong because each sample can have different durations, and therefore the endDate needs not reproduce the exact same chronological order as the startDate.
This causes the invariant check on `first <= last` being triggered in the wild (per Sentry)
Switch to `ORDER BY endDate DESC` instead.
> Use endDate DESC to lookup last sample

- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Client/VitalClientDelegates.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
All OS log interpolations are by default `%{private}@`. This means the interpolation is redacted outside of development contexts (not redacted in local Xcode builds, etc, but redacted in e.g. syslog and OSLogStore when no debugger is attached).
Since we want to be able to read logs in production (#37), we need most, if not all, our log interpolations to be marked as `%{public}@`, so that they are able to survive the redaction in production to help troubleshooting.
> [VIT-2680] Mark log interpolations with privacy: public

- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Always call HealthKit completion handlers, no matter whether the sync has failed or not.
If the phone has undesirable network condition [1] for an extensive period of time, it is currently possible for our SDK to fail to respond in background (by calling HealthKit completion handlers) 3 times in a row, and subsequently gets kicked off the background delivery list by HealthKit.
This is because we only call the HealthKit completion handlers on the happy "sync completed" path.
> https://developer.apple.com/documentation/healthkit/hkhealthstore/1614175-enablebackgrounddelivery
> If your app fails to respond three times, HealthKit assumes your app can’t receive data and stops sending background updates.
Make sure that:
1. the HealthKit completion handler is always called, regardless of the …
> [VIT-2682] Always call HealthKit completion handlers.

- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalCoreTests/VitalClientTests.swift
The singleton accessor is not serialized by a lock. So when it is accessed on multiple threads, especially during app launches, a race condition exists and causes multiple instances to be initialised and configured.
In one instance, `VitalClient.configure` intermittently sees a different `VitalClient` instance as to what a subsequent `VitalClient.setUserId` call sees, and this scenario is more prone to happen when there are other async calls in between any access to `VitalClient.shared` (where the current task may suspend and resume on a different thread). This causes the latter to crash, because the former sets the configuration on a different instance that the latter has no access to.
Protect the `shared` accessor with a lock, so only one instance can be created.
---
Also remove the …
> [VIT-2687] Serialize SDK singleton accessors.

- Sources/VitalCore/Calendar/GregorianCalendar.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Tests/VitalCoreTests/GregorianCalendarTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
Turns out that HKStatisticsQuery does not produce the same aggregation results as HKStatCollectionQuery, even when both are logically working on the exact same unit of time.
Since the results of HKStatCollectionQuery are what exactly matches the Apple Health app, adopt HKStatCollectionQuery for day summary.
1. Removed the now-disused `executeDaySummaryQuery` and `executeSampleQuery`.
2. Refactored `executeStatisticalQuery` so that it can support both hourly and daily granularity. It is also reworked to be an (cancellable) async function.
3. Tweaked how we query and put together the day summaries.
* For each quantity type, we now use only 1 `executeStatisticalQuery` call to cover the whole date range.
* All sums are rounded down to match Apple Health app behaviour.
7. Added some utilities …
> Use HKStatCollectionQuery for day summaries

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalHealthKitTests/StatisticalQueryTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitStorageTests.swift
Sentry flagged
Swift's semantic of its `withTaskCancellationHandler` primitive appears to be running the cancellation handler immediately on cancellation, no matter whether or not the main operation body has been executed.
This creates a scenario where — if `executeStatisticalQuery` is marked as cancelled before it gets executed — we would be attempting to ask HKHealthStore to start a stopped HKQuery, causing an NSInvalidArgumentException.
Check `Task.isCancelled` before we submit the `HKStatisticsCollectionQuery` to HKHealthStore to avoid this scenario.
> [VIT-2714] Check task cancellation before submitting HKQuery

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
To address VIT-2715 further, drop our ad-hoc HKSampleQuery-based solution for seeking first & last sample time for something better.
It turns out that HKStatisticsQuery produces the exact information we are looking for here:
> https://developer.apple.com/documentation/healthkit/hkstatistics/1615351-startdate
> If you calculated these statistics using a statistics query, this is the **earliest start date from all the samples** that match the query.
> https://developer.apple.com/documentation/healthkit/hkstatistics/1615067-enddate
> If you calculated these statistics using a statistics query, this is the **latest end date from all the samples** that match the query.
So switch `getFirstAndLastSampleTime` over to use HKStatisticsQuery, and eliminate the offending invariant check altogether. …
> [VIT-2715] Use HKStatQuery for first & last sample time

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Sources/VitalDevices/DeviceReading/GATTMeter.swift
Accu-Check appears to rely on BLE disconnection as a cue of transfer being completed, and users are prompted accordingly.
To make sure that this happens consistently, cancel the connection whenever we have completed a reading. Each `read()` call will attempt to reconnect from scratch anyway, so the cancellation should not be a concern for repeated calls (for whatever legitimate reasons).
Though note that the disconnection takes a few seconds to take effect, and it appears to be out of our control. The ball is in Core Bluetooth's court.
---
Also updated the iOS example app to separate the scanning and pair-n-read stage. By separating them, it also now supports re-reading from the device by tapping the button again.
> [VIT-2799] Disconnect peripheral on read completion

- Sources/VitalHealthKit/Extensions/Date.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
It was not quite apparent how the `Range<Date>` precondition failure in `queryStatisticsSample` can happen.
The most probable theory is that the device's system wall clock has changed backwards significantly, to the point where the `Date.now()` has moved before (some of the) `VitalAnchor.dates` we stored in the UserDefaults.
* Sanitise the start & end date at the beginning of `queryStatisticsSample`.
* `queryStatisticsSample` now throws a `VitalHealthKitClientError` if the input start & end dates do not make sense.
* `Date.dateAgo(_:_:)` now crashes if an expected `Date` was not produced, instead of silently returning an invalid value.
> [VIT-2890] Mitigate Range<Date> precondition failure

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/GATTMeterWithNoRACP.swift
- Sources/VitalDevices/Extensions/AnyPublisher+Utils.swift
The bulk of Omron (tested with real device) and Beurer (developer community research) BP devices do not implement Record Access Control Point (RACP), which means that we cannot retrieve history in the same way as we do with Accucheck Glucose devices.
The lack of RACP implies that:
1. There is no explicit "read complete" notification for us to stop listening — we have to infer it ourselves, generally based on timeouts.
2. These devices typically hold only the unsent records in its persistent memory. Once delivered, the records are often discarded (i.e., cannot be re-requested / won't be re-transfered).
---
This PR creates a different base class `GATTMeterWithNoRACP` to handle these RACP-less BLE devices properly:
* It listens for BP measurements with a 30 second listen timeout.
* When the …
> [VIT-2912] Support BP BLE devices with RACP unimplemented

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Sources/VitalDevices/DeviceReading/GATTMeter.swift
- Sources/VitalDevices/DeviceReading/GATTMeterWithNoRACP.swift
The read process sometimes was restarted multiple times.
It seems `_connectAndDiscoverCharacteristics` sometimes redelivers the characteristics consecutively, which then causes flatMapLatest in `read(device:)` to cancel the read process and restart it again.
Since the whole read process is stateful message passing, restarting prematurely without awaiting the Record Access Control Point response and/or without a reasonably long timeout can lead our read process into a stuck state.
Change it so that we take only the first valid value, thus avoiding the restarts.
Doing so requires some more refactoring to avoid cancelling the upstream `connect()` publisher subscription, which will cancel the CBPeripheral connection upon subscription cancellation.
---
Note that this does not address the edge …
> [VIT-3243] Fix the read process being unnecessarily restarted.

- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Extensions/APIClient+Extensions.swift
- Sources/VitalCore/Get/Source/DataLoader.swift
Wrap data tasks in UIKit background tasks, so that the historical stage has a better chance to run to completion when it initially starts in foreground.
> Wrap all data tasks in beginBackgroundTask

- Sources/VitalCore/Core/Client/Data Models/Patches/QuantitySample.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/SleepPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/SourceType.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/WorkoutPatch.swift
- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/GlucoseMeter1808.swift
- Sources/VitalDevices/Extensions/QuantitySample+Glucose.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalStatistics.swift
- Tests/VitalHealthKitTests/VitalHealthKitAnchorTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
1. Support `Sleep.sourceType`, `Workout.sourceType` and `QuantitySample.sourceType` for local reads to differentiate between iPhone data, Apple Watch data and Apple Health app manual entry.
* Example app usage: Disable heart rate chart for iPhone sleeps.
* Example app usage: Show sleep source type
3. Aligned all the `QuantitySample.type` values set by the SDK with the new source type definitions. Most notably, hourly statistics now use `type = multiple_sources`.
> VIT-4227: Support Source Type in iOS SDK

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalHealthKitTests/StatisticalQueryTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
1. Removed source bundle ID query for hourly statistics. 
3. Removed first and last sample time query for hourly statistics.
Neither of these features have been exposed in client facing schema. Most importantly, the planned introduction of activity raw samples would provide a superset of data that cover everything above. So there is no value to productize these.
Since we cut away 1 HKSourceQuery and + N HKStatisticsQuery (1 per VitalStatistics) calls, this would also provide a performance boost. Though it is probably temporary, as the anchored queries for activity raw samples would likely erase a portion of it.
> VIT-4227: Remove unused logic around hourly statistics

- Sources/VitalCore/Core/Client/Data Models/Base Models/LinkCRUD.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Link.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Summary.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Client/VitalClientDelegates.swift
- Sources/VitalCore/Core/Storage/VitalCoreStorage.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Tests/VitalCoreTests/VitalClientTests.swift
- Tests/VitalCoreTests/VitalJWTAuthSerializationTests.swift
Integrate VitalJWTAuth into APIClient & VitalClient as an opt-in mode.
The SDK still defaults to the (legacy) API Key mode.
> VIT-4322: VitalJWTAuth integration with APIClient & VitalClient

- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Client/VitalClientDelegates.swift
- Sources/VitalCore/Core/Logs/VitalLogger.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Apple DTS advice:
> https://developer.apple.com/forums/thread/705868
>
> Logging is fast enough to leave log points [1] enabled in your release build, which makes it easier to debug issues that only show up in the field.
For production (TestFlight and App Store) apps, critical/error/default logs are persisted (with OS managed log rotation), info logs are only kept in memory, and debug logs are dropped. Given that our log frequency is also fairly sparse, it would be way easier if we just have an always-on logging setup (provided that we use the log levels appropriately).
----
Simplify our logging setup by:
1. creating a set of static `OSLog.Logger`s (namespaces under the `VitalLogger` enum), which can be used from any scope/context. 
3. unconditionally log to OSLog; effectively deprecating …
> [VIT-2681] Use static OSLog loggers.

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Examples/iOS/Root.swift
- Examples/iOS/Settings/Settings.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
1. Improve information density
2. Separate demo configuration and SDK state.
3. Support switching between API Key mode and Sign-In Token Demo mode (emulating the JWT flow using the API Key for testing purpose).
> VIT-4345: Revamp iOS demo app settings screen

- Examples/iOS/Settings/Settings.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/UserCRUD.swift
- Sources/VitalCore/Core/Client/VitalClient+ControlPlane.swift
Factor out control plane API calls that are not accessible via User JWT, but still has value for early prototyping customers working with a full access API Key.
> VIT-4356: Create user and sign-in tokens without having first configured SDK

- Examples/iOS/Settings/Settings.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Tests/VitalCoreTests/VitalJWTAuthSerializationTests.swift
1. Ignore setUserId calls and emit an error OSLog, when the SDK has already signed in with User JWT (instead of crashing)
1. When signing in with User JWT, configure the SDK into User JWT Mode only when the initial token exchange is successful. In other words, if `VitalClient.signIn(withToken:)` failed, the SDK should be left in an unconfigured state.
1. Adjust JWT claim decoding logic to match backend changes.
1. Add some OSLog info logpoints
> VIT-4391: User JWT mode touchups

- Sources/VitalCore/Core/Client/Data Models/Base Models/ResourceData.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Blood Oxygen should be synced as an individual resource.
We added it as embedded samples of ManualSleepCreation, but in practice there is no observable correlation or causation between an Apple Watch sleep session and an Apple Watch writing blood oxygen sample. The later appears to be running on its own terms.
> VIT-4423: Add blood oxygen as an independent resource

- Sources/VitalCore/Core/Client/VitalClient.swift
- Tests/VitalCoreTests/VitalClientTests.swift
A new `localDebug` config field was added, but JSON decoding has not been updated to recognize its absence when upgrading from prior SDK versions.
Added test coverage
> VIT-4558: Fix VitalClient failed restoration due to new field

- Sources/VitalCore/Core/Client/ProtectedBox+BackgroundTask.swift
- Sources/VitalCore/Core/Client/ProtectedBox.swift
- Sources/VitalCore/Get/Source/DataLoader.swift
- Sources/VitalHealthKit/HealthKit/Models/BackgroundDeliveryPayload.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
1. endBackgroundTask needs to be called consistently to balance out the beginBackgroundTask call.
2. We now proactively perform an initial sync on newly requested resources, all of which would be wrapped by a single UIKit background task.
> Further improve historical stage resiliency against app moving into background

- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Link.swift
- Sources/VitalCore/Core/Client/VitalClient+VitalConnect.swift
1. Move the invite code sign-in flow to the SDK.
2. Expose the API for App API Key revoke.
3. Mark these APIs with `@_spi(VitalConnectApp)` so these would not show up in autocompletion under normal VitalCore imports.
> VIT-4754: Vital Connect private API for sign-in tokens

- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
Vital backend and API use [0, 100[ for percentage, rather than [0, 1[.
> CS1-28: Fix percent value scale

- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
This will allow any sleep generated by a user to be passed in (or by the iPhone itself). I am confident that before this PR, the code was filtering out sleeps generated by the iPhone as well (not just the ones generated manually by the user).
> [VIT-5323] Take lower case value in consideration when filtering sleeps

- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Client/VitalClientDelegates.swift
Expose SDK version so that Flutter and RN do not need to maintain their own copies.
> Formalize VitalClient.sdkVersion

- .swiftpm/xcode/xcshareddata/xcschemes/vital-ios-Package.xcscheme
- Sources/VitalCore/Core/Client/VitalClient.swift
- Tests/VitalCoreTests/VitalClientTests.swift
The availability of VitalCoreStorage is no longer contingent on the SDK having been configured.
cleanUp() now always attempts to clear VitalCoreStorage and VitalJWTAuth, irrespective of the SDK configuration state.
> VIT-5618: Fix cleanUp() not clearing sign-in state in some edge cases

- Sources/VitalCore/Core/Storage/VitalCoreStorage.swift
- Sources/VitalCore/Core/Storage/VitalSecureStorage.swift
We were using `HealthKit` and `SwiftUI` in places we shouldn't.
> [VIT-5634] Clean up rogue imports

- Examples/iOS/HealthKit Tab/HealthKitExample.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Introduce `VitalHealthKitClient.shared.pauseSynchronization` which can pause synchronisation without having to reset the SDK via `cleanUp()`.
This will also auto-trigger a sync on unpause.
> CS1-119: iOS: Ability to Pause HealthKit Synchronization

- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
* Actually used the scaled value.
* Remove the extra *100 scaling for body fat percentage, now that the QuantitySample initializer guarantees that all `HKUnit.percent()` values are scaled from 0...1 to 0...100.
> CS1-122: Fix percentage value handling

- Examples/iOS/Settings/Settings.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
* Fixed broken parsing of token refresh error response. `FirebaseTokenRefreshErrorResponse` should be used instead of `FirebaseTokenRefreshError`.
* If the signed-in user is deleted, the SDK now self-resets as if `VitalHealthKitClient.shared.cleanUp()` is called.
* Resetting the Core SDK also resets the Health SDK auto-sync.
> VIT-5855: Improve SDK reset behaviour

- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Reset child SDKs only when we explicitly detect user invalidation via JWT Auth, or consumer app explicitly calling `signOut()`.
Stop relying on `VitalClient.status` to reset the Health SDK. This is because `VitalClient.status` can report a false negative "signed out" state when Keychain is inaccessible until first unlock.
Vital SDK client secrets are stored in the iOS Keychain.
> VIT-5976: Don't rely on VitalClient.status to reset Health SDK

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/Models/WritableVitalResource.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
Correctly model the HealthKit types -> VitalResource relationship as two tiers:
* a **required** `HKObjectType` set
* an optional `HKObjectType` set
This ensures that when we add more `HKObjectType`s into an existing composite resource like `activity`, we do not break the composite resource mapping just because permissions have never been requested on the new `HKObjectType`s.
> VIT-6473: Refactor HealthKit -> Vital Resource mapping

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
#120 addressed the mapping design issue itself, and fixed issues when we map background delivery callbacks (in terms of `HKSampleType`) to an actionable VitalResource.
However, the historical stage was not addressed. We are still calling `VitalHealthKitClient.sync(_:)` on all individual resources (e.g. steps, vo2max) **in addition to** the composite resource (e.g. activity). We are supposed to only sync the composite resources (which as an umbrella syncs all the related individual resources).
This PR does further refactoring to ensure that the `sync(_:)` now accepts only **remapped resources** at compile time. Notably with this change, the iOS SDK is now fully aligned with Android SDK on how individual->composite resource remapping is handled.
> VIT-6512: HealthKit: Fix historical fetch resource remapping

- Examples/Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
- Sources/VitalCore/Core/Logs/VitalLogger.swift
- Sources/VitalLogging/LICENSE.txt
- Sources/VitalLogging/Locks.swift
- Sources/VitalLogging/LogHandler.swift
- Sources/VitalLogging/Logging.swift
- Sources/VitalLogging/MetadataProvider.swift
- Sources/VitalLogging/NOTICE.txt
- Sources/VitalLogging/README.txt
- VitalLogging.podspec
swift-log has no CocoaPods support.
So we have to resort to including a vendored copy to support both SPM and CocoaPods.
> VIT-6561: Include a vendored copy of swift-log@1.5.4

- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
The new approach:
1. Ask HealthKit to return all newly inserted (`HKQuantitySample`s) since we last queried.
* via `HKAnchoredObjectQuery`.
3. Takes the min-max of all sample timestamps, and then align the min-max to whole hours.
4. Recompute  steps/calories/etc hourly statistics of this time range.
This replaces the existing brute force approach of:
1. constantly querying 7 days of hourly statistics, wasting CPU time; and 
2. having to store hashes of the output statistics in order to deduplicate what we send to the backend.
TODO: Verify how SDK behaves when upgrading from an older version.
> VIT-6572: Overhaul how the time range to recompute hourly statistics is being decided

- Sources/VitalCore/Core/Client/Data Models/Base Models/UserCRUD.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
This PR adds an opt-in, backend-controlled feature flag `per_device_activity_ts`.
If enabled, the SDK would send the device-specific activity timeseries data (`type = phone | watch | unknown | etc`), in addition to the hourly statistics (marked with `type = multiple_sources`).
By coincidence, the new hourly statistics approach (#123) already discovers new device-specific activity samples as a byproduct. So to implement this feature, we don't need to do much more, besides embedding these already-available data in the outgoing payload.
> VIT-6573: Opt-in device-specific activity timeseries

- Examples/iOS/HealthKit Tab/HealthKitExample.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
Handle `.errorAuthorizationNotDetermined`, `.errorAuthorizationDenied`, and `.errorNoData` from HKAnchoredObjectQuery gracefully.
Treat them as "no data" rather than letting the error propagate out and failing the whole sync attempt.
---
This might be a plausible contributor of SDK sync issues, since our activity sync process could be disrupted by this issue, if VO2 Max read permission was not granted.
> VIT-6573: Improve anchored query error handling and logging

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient+Logs.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
#120 refactored the VitalResource -> HKObjectType mapping to have the concept of _required_ and _optional_ object types.
This PR breaks out a third category of _supplementary_ object types.
----
This came with an observation in a clean installation that:
1. We go through the `VitalResource.heartrate` ask flow.
2. We granted permission to `HKQuantityType(.heartrate)`.
3. Expected behaviour:
* Only `hasAskForPermission(.heartrate)` would report true.
3. Actual behaviour:
* `hasAskForPermission(.heartrate)` reports true as expected.
* [!] `hasAskForPermission(.activity)` unexpectedly reports true, because it listed `HKQuantityType(.heartrate)` as one of its optional object type.
----
This PR introduces an improved permission mapping ruleset:
1. Each sample type can only be claimed by one …
> VIT-6595: Fix a hasAskForPermission(_:) false positive

- Sources/VitalCore/Core/Log/PersistentLog.swift
- Sources/VitalCore/Core/Logs/VitalLogger.swift
The loggers are default to `.info`.
This means all `log()` calls would assemble the log message string in release build, even if VitalPersistentLogger is turned off.
This PR changes the default log level to `.error`, so that _most_ `log()` calls would become almost a no-op (check the log level, then quits early, since most logs are at `.info` level).
> VIT-6603: Change iOS SDK default log level to error

- Sources/VitalCore/Core/Client/Data Models/Base Models/UserCRUD.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/LocalSyncState.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
* Introduce a `LocalSyncState` that by default has 4-hour TTL.
* This allows us to revalidate `/sdk_sync_state` only when: (1) we do not have a known `LocalSyncState`; or that (2) the TTL has expired.
* Historical start date is now memoized, so all resources will use the exact same start date.
* Exception: When the user ingestion start date was set, that value from backend always takes precedence.
> VIT-6597: Caching SDK sync state

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Examples/iOS/Devices Tab/DevicesExample.swift
- Examples/iOS/Devices Tab/Libre1Connection.swift
- Examples/iOS/Link Creation/LinkCreation.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/BloodPressureDataPoint.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/ResourceData.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/TimeSeriesDataPoint.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/ActivityPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/BloodPressureSample.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/BodyPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/QuantitySample.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/SleepPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/TaggedPayload.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/WorkoutPatch.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/GlucoseMeter1808.swift
- Sources/VitalDevices/DeviceReading/Libre1Reader.swift
- Sources/VitalDevices/DeviceReading/VerioGlucoseMeter.swift
- Sources/VitalDevices/Extensions/QuantitySample+Glucose.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Tests/VitalDevicesTests/Libre1ReaderTests.swift
- Tests/VitalHealthKitTests/VitalHealthKitFreeFunctions.swift
Change:
* Timeseries API -> Grouped Timeseries API
Rename:
* TimeSeriesDataPoint -> ScalarSample
* BloodPressureDataPoint -> BloodPressureSample
* QuantitySample -> LocalQuantitySample
* BloodPressureSample -> LocalBloodPressureSample
Remove:
* ScalarSample.id
* BloodPressureSample.id
> VIT-6623: Catch up with API deprecations Pt.1

- Sources/VitalCore/Calendar/GregorianCalendar.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/LinkCRUD.swift
- Sources/VitalCore/Core/Client/Data Models/Gets/Activity.swift
- Sources/VitalCore/Core/Client/Data Models/Gets/Body.swift
- Sources/VitalCore/Core/Client/Data Models/Gets/Sleep.swift
- Sources/VitalCore/Core/Client/Data Models/Gets/Timeseries.swift
- Sources/VitalCore/Core/Client/Data Models/Gets/Workout.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/TaggedPayload.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/UserConnection.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Endpoints+Extensions.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Link.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Summary.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Storage/VitalCoreStorage.swift
- Sources/VitalDevices/DeviceManager+Brands.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalCoreTests/ProviderTests.swift
- Tests/VitalCoreTests/VitalClientTests.swift
Changes:
* Standard Link API response
Rename:
* UserConnection.Slug -> Provider.Slug
Addition:
* `calendar_date` on summaries
* Link Password Provider & Complete Password Provider MFA
Removal:
* `date` from body and activity
* `daily_movement` from activity
* Sleep Stream endpoint
> VIT-6623: Catch up with API deprecations Pt.2

- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Endpoints+Extensions.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
Timeseries methods missing support for the `cursor` parameter
> VIT-6623: Catch up with API deprecations Pt.3

- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
`/grouped` should only be appended to GET endpoints, not the POST endpoints.
> VIT-6623: Fix timeseries endpoint path

- Examples/iOS/Root.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Storage/VitalGistStorage.swift
- Sources/VitalCore/Core/Storage/VitalSecureStorage.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Sources/VitalCore/Keychain/Source/KeychainSwiftDistrib.swift
We currently store `VitalJWTAuthRecord` in Keychain.
It appears that our host apps could be woken up by iOS before the iOS Keychain is accessible after first unlock.
We had run into issues during this time window (#114) where we treat "keychain inaccessible" as no record, and therefore `VitalClient.status` reports a signed-out state. This is despite a valid `VitalJWTAuthRecord` sitting in the iOS Keychain, just not being accessible due to timing with OS data protection.
While #114 patched the issue by restructuring the [Core SDK SignOut -> Child SDK Reset] broadcast not to rely on `VitalClient.status`, it does not resolve the issue of both `VitalClient.status` and `VitalClient.currentUserId` reporting a false negative (signed-out state) during this time window.
This PR tackles this false …
> VIT-6644: Fix VitalClient.status false negative when keychain is inaccessible

- Examples/iOS/Devices Tab/DeviceConnection.swift
- Examples/iOS/Devices Tab/Libre1Connection.swift
- Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Logs/VitalLogger.swift
- Sources/VitalDevices/DeviceReading/BloodPressureReader1810.swift
- Sources/VitalDevices/DeviceReading/GATTMeter.swift
- Sources/VitalDevices/DeviceReading/GATTMeterWithNoRACP.swift
- Sources/VitalDevices/DeviceReading/GlucoseMeter1808.swift
- Sources/VitalDevices/DeviceReading/Libre1Reader.swift
- Sources/VitalDevices/DeviceReading/VerioGlucoseMeter.swift
- Sources/VitalDevices/Integration/PostSamples.swift
- Sources/VitalDevices/Models/Brand.swift
Mark timeseries POST methods as `@_spi(VitalSDKInternals)`.
Mark `checkConnectedSource` as `@_spi(VitalSDKInternals)`.
Devices SDK would now try to auto-post glucose and blood pressure samples after reading them, if the Core SDK has signed-in with a user.
> VIT-6646: Device SDK auto-posting samples

- Sources/VitalCore/Keychain/Source/KeychainSwiftDistrib.swift
#145 changed our Keychain fetch logic to handle all errors explicitly, rather than lumping all errors & no data scenarios into an overloaded `nil`.
This PR backfills the missing handling of the expected `errSecItemNotFound` error.
> VIT-6662: Handle the Keychain errSecItemNotFound error

- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Proactively try to create a connected source, after the user has gone through the HealthKit permission flow successfully (i.e. did not cancel the prompt).
Also remove the `checkConnectedSource` caching (a persistent flag tracking if the CS has been created):
* In the HealthKit sync process, we would call this as part of the LocalSyncState revalidation logic, so it is already covered by the same 4-hour TTL.
* In Devices SDK, the reading happens somewhat sparingly in absence of BLE background scanning and auto-send support. So it is fine to have it calling the API without caching.
> VIT-6663: iOS: Try to proactively create connected source on successful Ask

- Sources/VitalHealthKit/HealthKit/Models/BackgroundDeliveryPayload.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Whenever we spawn sync work in foregorund, protect them with a UIKit background task.
This ensures that they have a better chance to run to completion, should the user decide to background the app at any time.
> VIT-6992: Protect foreground sync work with UIKit background task

- .github/workflows/run_ci.yml
- Examples/iOS/Settings/Settings.swift
- Sources/VitalCore/Core/Client/VitalClient.swift
- Sources/VitalCore/Core/Log/PersistentLog.swift
- Sources/VitalCore/Core/Storage/VitalGistStorage.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads+MenstrualCycle.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient+Logs.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
- Tests/VitalHealthKitTests/StatisticalQueryTests.swift
Overlap read and upload, so we maximize the use of limited background execution time.
```
.read -> .upload
.read  -> .upload
.read -> .upload
(fin)
```
> VIT-7018: Overlap read and upload

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Reading individual HKSample off a high-frequency timeseries is a painfully slow process — as compared to using HKStatisticalCollectionQuery — due to the XPC overhead. 
Remove the embedded timeseries data from the local `read()`, since this ain't going to be an tolerable performance for data visualization / UI use case.
> VIT-7052: Remove embedded timeseries from local read()

- Sources/VitalHealthKit/HealthKit/Models/BackgroundDeliveryPayload.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Sources/VitalHealthKit/UI/ForEachVitalResource.swift
iOS does not seem to like high CPU usage in background. Syncing multiple resources concurrently seems to be leading to our host app process being frozen.
Change it so that:
1. We now only sync concurrently in foreground.
2. In background, we sync resources **serially** with batching and prioritisation.
* Callouts made within a 16ms window are batched up.
* Within each batch, notified resources are deduplicated, are sorted by their priority, and are then scheduled for execution serially.
> VIT-7076: Buffer, dedup and batch execute background delivery callouts

- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Some higher priority resource might have errored, cancelled or timed out on their historical stage sync. Then they are stuck in said states, since there is no new data written to HealthKit to trigger a background delivery.
This can in turn block the lower priority resources from syncing, as they are stuck in the _deprioritized_ state due to higher priority resources not having all completed their historical stage.
--
This PR updates the `scheduleUnnotifiedResourceRescue` routine — which runs shortly after app launch to start sync attempts on eligible resources to ensure forward progress for all. 
* The routine has been starting sync on resources that has no sync attempt.
* This PR expands criteria to app launch on any last errored, cancelled, timed out resources, so we "rescue" them from …
> VIT-7406: iOS: Lower priority resource is stuck when higher priority resource has errored

- Examples/iOS/HealthKit Tab/HealthKitExample.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/ResourceData.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/MealPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/QuantitySample.swift
- Sources/VitalCore/Core/Encodable/AnyEncodable.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
Apologies for the large PR, but in my defence most of the lines is just listing all the different nutrients in different forms 🙈
> [VIT-7375] Apple Health Kit: add support for nutritional data

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Some customers want the Ask API to request health data permissions for their own direct HealthKit use & whatever Vital SDK needs in one shot.
Extend the Ask API with two new optional arguments: `extraReadPermissions` and `extraWritePermissions`.
> VIT-7449: Support extra permissions in Ask

- Sources/VitalCore/Core/Client/ProtectedBox.swift
- Sources/VitalCore/JWT/VitalJWTAuth.swift
- Sources/VitalDevices/DeviceReading/Libre1Reader.swift
- Sources/VitalDevices/NFC/NFC.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalCoreTests/VitalClientTests.swift
Replace all checked continuation usage with unsafe continuation.
Ref:
- [RevenueCat's iOS 18 Checked Continuation crash workaround](https://github.com/RevenueCat/purchases-ios/issues/4177)
- [swiftlang/swift tracking issue](https://github.com/swiftlang/swift/issues/75952)
- [Apple developer forum thread](https://developer.apple.com/forums/thread/761580)
> VIT-7468: Workaround iOS 18 CheckedContinuation crash

- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
After #242 was implemented that enables additional `HKObjectType` types to be requested there's a need to resolve the underlying HealthKit permissions from `VitalResource`. This change simply exposes the `toHealthKitTypes` requirements method as `healthKitRequirements(for resource: VitalResource)` via the `VitalHealthKitClient`.
Given that now we're able to request additional permissions for direct HealthKit access it makes sense to track the requested read permissions internally in a more atomic fashion - using `HKObjectType` instead of `VitalResource`. This is handy when we want to detect whether new permissions can be requested in cases when:
1. The user has upgraded to a new version of the app with the updated list of HealthKit permissions.
2. The user has upgraded the iOS version …
> Expose HealthKit requirements for VitalResource

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalHealthKitTests/SampleTypeTests.swift
- Tests/VitalHealthKitTests/StatisticalQueryTests.swift
The cause of the reported crash is likely that both `HKHealthStore.execute(_:)` and `HKHealthStore.stop(_:)` were not synchronized with the mutual exclusion inside `CancellableQueryHandle`. So a race condition amongst them can arise and cause the " already been executed and cannot be executed again" NSException.
---
Per documentation, `HKHealthStore.stop(_:)` was only intended for long-running queries with store observation.
> https://developer.apple.com/documentation/healthkit/hkhealthstore/1614173-stop
>
> Either an [HKObserverQuery](https://developer.apple.com/documentation/healthkit/hkobserverquery) instance or an [HKStatisticsCollectionQuery](https://developer.apple.com/documentation/healthkit/hkstatisticscollectionquery) instance.
>
> Use this method on long-running queries only. …
> VIT-7712: Stop using HKHealthStore.stop(_:)

- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
Always use `GregorianCalendar.utc` when we convert calendar dates to/from `StoredAnchor.date` so there can be no surprise when time zone changes.
> DEV-223: Tweak how we store StoredAnchor.date for activity

- Sources/VitalHealthKit/HealthKit/Storage/SyncProgressStore.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Prioritisation did not kick in the expected way. Tweak the criteria again to restore the expected execution order.
> Tweak historical stage prioritization logic again

- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Tests/VitalHealthKitTests/VitalHealthKitClientTests.swift
As part of the mitigation of some rare priority inversion encounters inside HealthKit internals, SDK 1.4.1 migrated to use the official asynchronous `getRequestStatusForAuthorization` method to obtain the request status.
However, `-getRequestStatusForAuthorization` ended up being more problematic, causing intermittent crashes at `voucher_adopt` (libdispatch level).
This PR partially reverts the mitigation, where we replace `-getRequestStatusForAuthorization` with the good old `-authorizationStatusForType:`.
The combination of `-authorizationStatusForType:` + a high QoS DispatchQueue appears to function normally in one reproducible case that would have otherwise crashed at `voucher_adopt`.
> DEV-261: Revert back to use -authorizationStatusForType:

- Examples/iOS/HealthKit Tab/HealthKitExample.swift
- Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/Models/WritableVitalResource.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
* `ask(...)` now supports an _optional_ data type allowlist to restrict what HealthKit data types the SDK can request authorization for.
* Mark a few SDK currency value types as `Sendable`.
* Added a request restriction demo mode to the iOS Example app.
> DEV-328: iOS SDK: Health data type allowlist

- Sources/VitalCore/Core/Storage/VitalGistStorage.swift
- Sources/VitalHealthKit/HealthKit/AppStateTracker.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/UserHistoryStore.swift
- Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
- Tests/VitalHealthKitTests/UserHistoryStoreTests.swift
* Introduce `UserHistoryStore` to keep a local on-device record of time zone and wheelchair use of the past 30 days.
* Use this record to improve activity daily summary recomputation.
* When an end user moves to a new time zone, it no longer causes also the summaries for three prior days (`activityStatsDaysToLookback`) to change to the new time zone. Instead, we would compute those days using the time zone recorded by `UserHistoryStore` for that day.
> DEV-319: iOS SDK: Locally track time zone and wheelchair use history

- Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/ActivityPatch.swift
- Sources/VitalCore/Core/Storage/VitalCoreStorage.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Sources/VitalHealthKit/HealthKit/UserHistoryStore.swift
* `activity`:
* Compute `distanceWheelchair` sum & `pushCount` sum in Activity Day Summary.
* Include `wheelchairUse` from UserHistoryStore.
* `distance`:
* Now compute hourly statistics & per-device activity timeseries for both `distanceWalkingRunning` and `distanceWheelchair`.
> DEV-320, DEV-321: Update activity and distance resources with Wheelchair Mode support

- Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/BodyPatch.swift
- Sources/VitalCore/Core/Client/Data Models/Patches/QuantitySample.swift
- Sources/VitalHealthKit/HealthKit/Abstractions.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads+Body.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads+MenstrualCycle.swift
- Sources/VitalHealthKit/HealthKit/HealthKitReads.swift
- Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift
- Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
- Tests/VitalHealthKitTests/VitalResourceTests.swift
1. Use AnchoredQuery on all 5 body quantity types to gather the changed dates.
2. Find the minimum and maximum changed dates.
3. Fetch all body quantity samples that fall inside this date range.
This was a past approach for Activity Summary. We ditched it for Activity because of performance issues with the amount of high(er)-frequency timeseries involved. However, Body is low frequency, typically _at most_ once or twice per day. So this approach should work fine.
> DEV-323: New approach to sync Body Summary
