Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift, Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalCore/Core/Storage/VitalCoreStorage.swift, Sources/VitalCore/Core/Storage/VitalSecureStorage.swift
Small refactoring so testing is possible
=> Preparation for testing

Sources/VitalCore/Core/Client/Data Models/Patches/ActivityPatch.swift, Sources/VitalCore/Core/Client/Data Models/Patches/TaggedPayload.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Summary.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift, Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalHealthKit/HealthKit/Abstractions.swift, Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift, Tests/VitalCoreTests/VitalClientTests.swift
=> [VIT-1727] Pass the user's timezone

Sources/VitalCore/Core/Client/Data Models/Base Models/ResourceData.swift, Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift, Sources/VitalHealthKit/HealthKit/Abstractions.swift, Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift, Tests/VitalHealthKitTests/VitalHealthKitReadsTests.swift
Currently HRV is associated with Sleep, but intra day readings are possible. So we should expose HRV by itself.
=> Enable HRV by itself

Sources/VitalHealthKit/HealthKit/Models/BackgroundDeliveryPayload.swift, Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
=> [VIT-2665] Use the new query in iOS 15

Sources/VitalHealthKit/HealthKit/Abstractions.swift
Sentry flagged an invariant check violation.
The check was a strong precondition failure, since logic dictates that, given the same sample time range predicate, if `firstSample` exists then `lastSample` must also exist, and vice versa. This invariant has also been upheld against various internal tester's fully populated HealthKit databases.
But apparently this can happen in the wild, persumably an Apple SDK bug or a random blip.
So downgrade to assertion failure so that it asserts only in debug builds. For release builds, we would take the start ..< end of the sample, which should still be a fair approximation.
=> [VIT-2715] Downgrade a precondition to a debug-build-only assertion.

Sources/VitalHealthKit/HealthKit/Abstractions.swift, Tests/VitalHealthKitTests/StatisticalQueryTests.swift
There were a couple specifically crafted lab scenarios where `withTaskCancellationHandler` + `withCheckedThrowingContinuation` does not cancel and return control as expected. The issue is particularly challenging to workaround, since HealthKit does not deliver a cancellation error to the result handlers when a query has begun to execute, but is then interrupted via `HKHealthStore.stop(HKQuery)`.
To be on the safe side, remove the use of this combo for now.
We now check for task cancellation only before attempting to start an `HKQuery`. If the task is cancelled after the query has started, we let it run to completion, despite the result sent via the continuation being practically dropped by Swift Concurrency.
=> [VIT-2714] Check for cancellation only before starting an HKQuery

Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
It appears that the iOS 15+ HKObserverQuery might pass us `HKSampleType`s that is outside the conditions we specified via `descriptors`, since `sampleTypeToVitalResource(2)` does not seem to contain any missing mapping as required by `observedSampleTypes()`.
Mitigate this by filtering out any unsolicited types before proceeding.
=> [VIT-2889] Filter out unsolicited sample types from HKObserverQuery

Sources/VitalCore/JWT/VitalJWTAuth.swift
Rough skeleton of the VitalJWTAuth actor managing the JWT token sign-in, refresh & persistence.
=> VIT-4319: VitalJWTAuth skeleton

Sources/VitalCore/JWT/VitalJWTAuth.swift
Implement the JWT token refresh flow.
=> VIT-4320: VitalJWTAuth token refresh flow

Sources/VitalCore/JWT/VitalJWTAuth.swift, Tests/VitalCoreTests/VitalJWTAuthSerializationTests.swift
Implement the JWT sign-in (initial token exchange) flow
=> VIT-4321: VitalJWTAuth sign-in flow

Examples/iOS/Devices Tab/DevicesExample.swift, Examples/iOS/HealthKit Tab/HealthKitExample.swift, Examples/iOS/Settings/Settings.swift, Sources/VitalCore/Core/Client/NetworkError.swift, Sources/VitalCore/Core/Client/VitalClient.swift
Help testing the User JWT mode
=> VIT-4339: Support running iOS demo app against local vital-api

Examples/iOS/Devices Tab/Models/Devices+Support.swift, Sources/VitalCore/Core/Client/Data Models/Patches/Provider.swift, Sources/VitalDevices/DeviceManager+Brands.swift
Add OneTouchBLE to `Provider.Slug`
=> VIT-4458: OneTouch support touch-ups

Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
When `checkBackgroundUpdates` is triggered in response to a successful `ask(...)` call, it is only injected with the set of resources **being requested**, which does not include previously asked resources.
This may subsequently cause HealthKit observers to be (re-)created only for that subset of resources.
This means the automatic update may not be working properly for API consumers that use `ask(...)` incrementally, i.e., requests disjoint subsets of resources with separate calls. 
This PR:
1. Changed `checkBackgroundUpdates` to no longer accept an injected set of `VitalResource`, and instead depends on the store to enumerate the set of "already asked" VitalResources.
2. `checkBackgroundUpdates` now reconfigures the observer task only if the VitalResource set has changed. This should …
=> VIT-4552: Fix checkBackgroundUpdates not setting up all observers when ask(_:) is used incrementally

Sources/VitalCore/Core/Client/Data Models/Patches/WorkoutPatch.swift, Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
We were missing these two properties when sending data for workouts.
=> [VIT-4735] Added elevation + moving time

Sources/VitalCore/Core/Client/VitalClient.swift
Attempt SDK auto-config on first access via `VitalClient.shared`, `VitalClient.status` or `VitalClient.currentUserId`.
Aligns (mostly) with Android SDK behaviour, which always reads from the persistent shared preferences as its source of truth, and does not require an explicit `configure(...)` or `automaticConfiguration()` call by the SDK consumer to rehydrate the SDK state.
=> VIT-5621: iOS: attempt SDK auto-config on first access

Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift, Sources/VitalHealthKit/HealthKit/Abstractions.swift, Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift, Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift, Tests/VitalHealthKitTests/SampleTypeTests.swift
Add test cases to verify mapping.
=> CS1-173: Fix incomplete sample type mapping causing crashes

Examples/iOS/Root.swift, Examples/iOS/Settings/Settings.swift, Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalCore/Core/Client/VitalClientDelegates.swift, Sources/VitalCore/Core/Log/PersistentLog.swift, Sources/VitalCore/Core/Logs/VitalLogger.swift, Sources/VitalCore/Core/Storage/VitalCoreStorage.swift, Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/Storage/VitalHealthKitStorage.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient+Logs.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift, Tests/VitalCoreTests/VitalClientTests.swift
=> VIT-6561: Persistent Logging with shareable log archives

Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalCore/Core/Log/PersistentLog.swift, VitalCore.podspec, VitalDevices.podspec, VitalHealthKit.podspec
Each log category dump process should advance independently.
=> VIT-6561: Track lastDump separately for each category

Examples/Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Examples/iOS/Settings/Settings.swift, Package.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift, Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalCore/Core/Client/VitalClientDelegates.swift, Sources/VitalCore/Core/Log/PersistentLog.swift, Sources/VitalCore/Core/Logs/VitalLogger.swift, Sources/VitalCore/JWT/VitalJWTAuth.swift, Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient+Logs.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
OSLogStore is too slow, and are suspectible to missing logs.
Switch to synchronous writes to log files.
=> VIT-6561: Ditch OSLogStore and write to log files directly

Sources/VitalCore/Core/Client/Data Models/Gets/Activity.swift, Sources/VitalCore/Core/Client/Data Models/Gets/Body.swift, Sources/VitalCore/Core/Client/Data Models/Gets/Sleep.swift, Sources/VitalCore/Core/Client/Data Models/Gets/Source.swift, Sources/VitalCore/Core/Client/Data Models/Gets/Workout.swift, Sources/VitalCore/Core/Client/Data Models/Patches/TaggedPayload.swift, Sources/VitalCore/Core/Client/Data Models/Patches/UserConnection.swift, Sources/VitalCore/Core/Client/Data Models/Patches/VitalAPIResource.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Endpoints+Extensions.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Link.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Summary.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+User.swift, Sources/VitalCore/Core/Client/VitalClient.swift, Sources/VitalCore/Core/Storage/VitalCoreStorage.swift, Sources/VitalDevices/DeviceManager+Brands.swift, Sources/VitalHealthKit/HealthKit/Abstractions.swift, Tests/VitalCoreTests/ProviderTests.swift, Tests/VitalCoreTests/VitalClientTests.swift
Support status & resource availability
=> VIT-6619: Update userConnectedSources

Sources/VitalCore/Core/Client/Endpoints/VitalClient+Endpoints+Extensions.swift, Sources/VitalCore/Core/Client/Endpoints/VitalClient+Timeseries.swift
=> VIT-6643: Catch up with API deprecations Pt.5

Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
If HealthKit notifies about multiple types of data being available, right now we serialize the processing.
So if there are five items being notified in one app wake-up, the last item would be delayed by the cumulative execution time of the former four items — including the time they take to upload to Vital API. This may result in violating the 30 second background time limit.
Instead, spawn sync work on all of them, and let them all progress concurrently.
=> VIT-6991: Allow multiple resource syncs to run concurrently

Sources/VitalHealthKit/HealthKit/VitalHealthKitClient.swift
Flood of HealthKit callouts (10-100s) are observed on some phones.
This seems to be caused by some HealthKit writer apps writing each sample to HKHealthStore individually, rather than writing them in batches.
Defend against this malpractice by ensuring that:
1. only one `sync(_:)` can be in flight for each `RemappedVitalResource` at any given time.
2. other attempts would simply wait for the in-flight attempt to complete, then quit early.
=> VIT-6993: Ensure sync logic is always single flight against flood of HealthKit callouts

Sources/VitalCore/JWT/VitalJWTAuth.swift
#268 did add detection to `VitalJWTAuth.getRecord()`.
But signIn had been relying on `VitalJWTAuth.getGist()` and there is (1) no detection for dangling keychain items there and (2) no cross-check with the keychain item when it is available. So the issue persists where `signIn` sees a false positive sign-in & therefore decided not to proceed to sign-in.
=> DEV-117: Detect another case of dangling keychain items post app reinstallation

Examples/iOS/HealthKit Tab/HealthKitExample.swift, Sources/VitalCore/Core/Client/Data Models/Base Models/ResourceData.swift, Sources/VitalCore/Core/Client/Data Models/Base Models/VitalResource.swift, Sources/VitalCore/Core/Client/Data Models/Patches/QuantitySample.swift, Sources/VitalHealthKit/HealthKit/Abstractions.swift, Sources/VitalHealthKit/HealthKit/HealthKitReads.swift, Sources/VitalHealthKit/HealthKit/Models/CoreModels+Extensions.swift, Sources/VitalHealthKit/HealthKit/Models/VitalResource+HealthKit.swift
* [draft] pending testing post bgpull implementation
=> [DEV-326] HealthKit: support new timeseries resources

Sources/VitalCore/Core/Client/Data Models/Patches/BodyPatch.swift
Default serialization does not match what we expect in the backend
=> DEV-323: Fix BodyPatch.timeZones serialization
